[General]
loglevel = notify
show-error-page-for-reject = true
allow-wifi-access = false
all-hybrid = true
ipv6 = false
test-timeout = 5
proxy-test-url = http://www.gstatic.com/generate_204
geoip-maxmind-url = https://github.com/Toovooo/Rules/raw/master/Script/Private-GeoIP-CN.mmdb
exclude-simple-hostnames = true
dns-server = 223.5.5.5, 119.29.29.29
hijack-dns = 8.8.8.8:53, 8.8.4.4:53
read-etc-hosts = true
http-api-web-dashboard = false
use-default-policy-if-wifi-not-primary = false
skip-proxy = www.baidu.com,yunbusiness.ccb.com,wxh.wo.cn,gate.lagou.com,www.abchina.com.cn,www.shanbay.com,login-service.mobile-bank.psbc.com,mobile-bank.psbc.com,id6.me
always-real-ip = *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com*.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.battlenet.com.cn, *.battlenet.com, *.blzstatic.cn, *.battle.net
hide-vpn-icon = true
wifi-assist = false
update-url = https://github.com/Toovooo/Rules/raw/master/Shadowrocket/Shadowrocket.conf
force-http-engine-hosts = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net


[Proxy Group]
Apple = select, 香港, 美国, 日本, 新加坡,  no-alert=0, hidden=0, include-all-proxies=0
Spotify = select, 香港, 美国, 日本, 新加坡, no-alert=0, hidden=0, include-all-proxies=0
Telegram = select, 香港, 美国, 日本, 新加坡,  no-alert=0, hidden=0, include-all-proxies=0
YouTube = select, 香港, 美国, 日本, 新加坡,  no-alert=0, hidden=0, include-all-proxies=0
Epic = select, 香港, 美国, 日本, 新加坡,  no-alert=0, hidden=0, include-all-proxies=0
香港 = url-test, update-interval=0, policy-regex-filter=🇭🇰|香港|HK|湾仔|港仔|九龙|HongKong, no-alert=0, hidden=0, include-all-proxies=0
新加坡 = url-test, update-interval=0, policy-regex-filter=新加坡|坡|狮城|SG|Singapore, no-alert=0, hidden=0, include-all-proxies=0
美国 = url-test, update-interval=0, policy-regex-filter=🇺🇸|美国|US|华盛顿|俄勒冈|内华达|拉斯维加斯|蒙大纳|怀俄明州|菲尼克斯|阿尔伯克基|丹佛|哥伦比亚, no-alert=0, hidden=0, include-all-proxies=0
日本 = url-test, update-interval=0, policy-regex-filter=🇯🇵|日本|JP|东京|大阪|名古屋|福冈|仙台|京都|川日|泉日|埼玉|沪日|深日, no-alert=0, hidden=0, include-all-proxies=0

[Rule]
RULE-SET,https://github.com/Toovooo/Rules/Shadowrocket/List/AdBlock.list,REJECT
RULE-SET,https://github.com/Toovooo/Rules/Shadowrocket/List/YouTube.list,YouTube
RULE-SET,https://github.com/Toovooo/Rules/Shadowrocket/List/Telegram.list,Telegram
RULE-SET,https://github.com/Toovooo/Rules/Shadowrocket/List/Apple.list,Apple
RULE-SET,https://github.com/Toovooo/Rules/Shadowrocket/List/Spotify.list,Spotify
RULE-SET,https://github.com/Toovooo/Rules/Shadowrocket/List/Epic.list,Epic
GEOIP,CN,DIRECT
FINAL,YouTube

[URL Rewrite]

[Script]

[MITM]
enable = true
hostname = 
